### ISSUE TITLE
Add netlify-plugin-submit-sitemap

### ISSUE THREAD

**Issue by h-enk** [h-enk/henkverlinde.com#200]
```toml
[[plugins]]
  package = "netlify-plugin-submit-sitemap"

  [plugins.inputs]
    baseUrl = "https://henkverlinde.com/"
    sitemapPath = "/sitemap.xml"
    ignorePeriod = 0
    providers = [
      "google",
      "bing",
      "yandex"
    ]
```
